### ISSUE TITLE
Change `is_avalanching` protocol to one based on `std::[true|false]_type`

### ISSUE THREAD

**Issue by joaquintides** [boostorg/unordered#248]
Currently, hash function avalanching is indicated by the mere presence of a nested `is_avalanching` typedef (like `is_transparent`). Change that to requiring that `is_avalanching` is  `std::[true|false]_type` (or derived from those), in the same vein as propagate traits for allocators.

To keep backwards compatiblity, if `is_avalanching` is present but not (derived from) `std::[true|false]_type` , this must be taken as equivalent to `using is_avalanching = std::true_type`.

**Comment by pdimov** [comment]
I think what we want is: `hash_is_avalanching<H>` is

* derived from `std::true_type` when `std::is_void<H::is_avalanching>::value` is `true`
* otherwise derived from `std::integral_constant<bool, H::is_avalanching::value>`

in the case `H::is_avalanching` exists, of course.

This accepts `boost::integral_constant<bool, B>` and other non-`std` integral constants such as `mpl::bool_`.
